name: Publish

on: 
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@pageuppeopleorg'
      - name: Upgrade npm 🎉
        run: npm i -g npm@latest
      - run: npm i
      - run: npm test
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
      - name: version
        run: npm --no-git-tag-version --allow-same-version version ${{ steps.tag.outputs.new_tag }}
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
